---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apf-device-plugin
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-apf-device-plugin
  namespace: kube-system
  labels:
    tier: node
    app: apfdp
spec:
  selector:
    matchLabels:
      name: apf-device-plugin
  template:
    metadata:
      labels:
        name: apf-device-plugin
        tier: node
        app: apfdp
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: arm64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      serviceAccountName: apf-device-plugin
      containers:
      - name: kube-apfdp
        image: localhost:5000/github.com/intel/ipu-device-plugin:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "250m"
            memory: "40Mi"
          limits:
            cpu: 1
            memory: "200Mi"
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/device-plugins
          readOnly: false
        - name: plugins-registry
          mountPath: /var/lib/kubelet/plugins_registry
          readOnly: false
        - name: log
          mountPath: /var/log
        - name: config-volume
          mountPath: /etc/ipu-dp
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: plugins-registry
          hostPath:
            path: /var/lib/kubelet/plugins_registry
        - name: log
          hostPath:
            path: /var/log
        - name: config-volume
          configMap:
            name: apf-config
            items:
            - key: config.json
              path: config.json

---