apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vsp-daemonset
spec:
  selector:
    matchLabels:
      name: vsp
  template:
    metadata:
      labels:
        name: vsp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      hostNetwork: true
      automountServiceAccountToken: false
      containers:
      - name: appcntr1
        image: silpixa00400458:5000/intel-ipuplugin:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command: [ "/usr/bin/ipuplugin" ]
        args: [ "-v=debug"]
        volumeMounts:
        - name: vendor-plugin-sock
          mountPath: /var/run/dpu-daemon/
      volumes:
      - name: vendor-plugin-sock
        hostPath:
          path: /var/run/dpu-daemon/

