# Specify the base image
FROM gcc:latest
# Copy the program files
COPY nf.c /app/
# Set the working directory
WORKDIR /app
# Compile the program
RUN gcc -o nf nf.c
# Set the entry point
RUN chmod +x nf
CMD ["./nf"]